---
- name: Create /usr/local/bin directory
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    owner: root
    mode: "0755"

- name: Install log2ram v{{ log2ram_version }} script
  ansible.builtin.get_url:
    url: "{{ log2ram_remote_source }}/log2ram"
    dest: /usr/local/bin/log2ram
    owner: root
    mode: "0755"

- name: Create log2ram systemd units
  ansible.builtin.get_url:
    url: "{{ log2ram_remote_source }}/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    mode: "0644"
  loop: "{{ log2ram_systemd_services }}"
  notify:
    - Enable log2ram services
    - Reboot the system
