---
- name: Remove log2ram service
  ansible.builtin.service:
    name: log2ram
    state: stopped
    enabled: no
  tags: log2ram-uninstall

- name: Remove log2ram-daily timer
  ansible.builtin.systemd:
    name: log2ram-daily.timer
    state: stopped
    enabled: no
  tags: log2ram-uninstall

- name: Remove files and directories
  ansible.builtin.shell: |
    rm -rf /etc/systemd/system/log2ram*
    rm /usr/local/bin/log2ram
    rm /etc/log2ram.conf
    rm -f /etc/logrotate.d/log2ram
    if [ -d /var/hdd.log ]; then
      rm -r /var/hdd.log
    fi
    rm /usr/local/bin/uninstall-log2ram.sh
  args:
    warn: no
  tags: log2ram-uninstall
