---
- name: Stop systemd log2ram services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ log2ram_systemd_services }}"
  tags: log2ram_uninstall

- name: Remove systemd log2ram units
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  loop: "{{ log2ram_systemd_services }}"
  tags: log2ram_uninstall

- name: Remove log2ram files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ log2ram_system_files }}"
  tags: log2ram_uninstall
