---
- name: Clean systemd journal
  ansible.builtin.command: journalctl --vacuum-size={{ log2ram_vacuum_size }}
  when: log2ram_journal_cleanup

- name: Enable log2ram services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - log2ram.service
    - log2ram-daily.timer

- name: Restart log2ram service
  ansible.builtin.service:
    name: log2ram.service
    state: restarted

- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: 300
